apiVersion: apps/v1
kind: Deployment
metadata:
  name: session20-gitops-app
  labels:
    app: session20-gitops-app
spec:
  replicas: 5
  selector:
    matchLabels:
      app: session20-gitops-app
  template:
    metadata:
      labels:
        app: session20-gitops-app
    spec:
      containers:
        - name: app
          image: nginx:1.27-alpine
          ports:
            - containerPort: 80
